#!/usr/bin/env python

#   This file is part of Augur - <http://github.com/winry-linux/augur>
#
#   Copyright 2017, Joshua Strot <joshua@winrylinux.org>
#
#   Augur is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Augur is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Augur. If not, see <http://www.gnu.org/licenses/>.

import argparse

from os import geteuid
from sys import argv

from augur.display import *
from augur.configuration import *
from augur.scraper import *
from augur.parser import *

# Exit if root
if geteuid() == 0:
    print("=> This program cannot be ran as root")
    exit(0)

# Set up the argument parser, add the needed options
parser = argparse.ArgumentParser(
    description='Check the Winry repository for updates from the AUR.')
parserGroup = parser.add_mutually_exclusive_group()
parserGroup.add_argument('-u', "--update", action="store_true", help="Update the list of AUR packages and versions")
parserGroup.add_argument('-c', "--check", action="store_true", help="Check the list of AUR packages again the repository")
parserGroup.add_argument('-b', "--blacklist", type=str, metavar="PACKAGE", help="Blacklist a package from being checked")
parserGroup.add_argument('-w', "--whitelist", type=str, metavar="PACKAGE", help="Whitelist a package so it is checked again")
parserGroup.add_argument('-p', "--printblack", action="store_true", help="Print the blacklist")

# Output help if no argument is passed, exit
if len(argv) == 1:
    asciiArt.banner()
    parser.print_help()
    exit(1)

# Parse args
args = parser.parse_args()

# configure Augur
config = configure.loadConfiguration()

# Run the program
if args.update:
    print("=> Updating cache")

    # Load cache
    cachePath = configure.checkCache(True)

    # Download the AUR package list
    scrape.scrapeAur(config["AURUrl"], cachePath)
elif args.check:
    print("=> Checking for version changes")

    # Load cache
    cachePath = configure.checkCache(False)

    # Load blacklist
    blacklistPacks = blacklist.readBlacklist()

    # Load winry-testing packages
    winryPackages = parseRepo.parsePackages(config["Mirror"])

    # Load AUR packages
    aurPackages = load.loadAurCache()

    # Compare the packages
    compare.compare(winryPackages, aurPackages, blacklistPacks)
elif args.blacklist:
    # Blacklist the defined package
    blacklist.addBlacklist(args.blacklist)
elif args.whitelist:
    # Remove a package from the blacklist
    blacklist.whitelist(args.whitelist)
elif args.printblack:
    # Print the blacklist
    blacklist.printBlacklist()
